name: Deploy via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS via SCP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar SSH
      run: sudo apt-get install openssh-client -y

    - name: Adicionar chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copiar arquivos para o servidor via SCP
      run: |
        shopt -s extglob
        scp -r !(node_modules|.git|.github) ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/disciplinas.joseolinda.com.br/public_html/2025.1/pweb1/praticas/
